[package]
name = "monty-hall"
version = "0.1.0"
authors = ["Craig Barber <craigb@mojotech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
itertools = "0.10.1"
